[package]
name = "clicker"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.19.4"
winit = "0.29.15"
pollster = "0.3.0"
cfg-if = "1"
env_logger = "0.11.3"
log = "0.4"
bytemuck = { version = "1.12", features = [ "derive" ] }
anyhow = "1.0"
web-time = "1.1.0"
nanorand = "0.7.0"